components:
  schemas:
<<<<<<< HEAD
    FileInformation:
      description: 'Basic public information container for files registered with the
        Internal File

        Registry service.'
      properties:
        file_id:
          description: Public identifier of the file associated with the given information
          title: File Id
          type: string
        sha256_hash:
          description: SHA256 hash of the unencrypted file content encoded as hexadecimal
            values as produced by hashlib.hexdigest().
=======
    DatasetInformation:
      description: Container bundling public information for a dataset.
      properties:
        dataset_id:
          description: Public accession of a dataset.
          title: Dataset Id
          type: string
        file_information:
          description: Public information on all files belonging to a dataset.
          items:
            $ref: '#/components/schemas/FileInformation'
          title: File Information
          type: array
      required:
      - dataset_id
      - file_information
      title: DatasetInformation
      type: object
    FileInformation:
      description: 'Public information container for files registered with the Internal
        File

        Registry service.'
      properties:
        file_id:
          description: Public identifier of the file associated with the given information
          title: File Id
          type: string
        sha256_hash:
          description: SHA256 hash of the unencrypted file content encoded as hexadecimal  values
            as produced by hashlib.hexdigest().
>>>>>>> ba1695c (WIP batch mode and migration)
          title: Sha256 Hash
          type: string
        size:
          description: Size of the unencrypted file in bytes.
          exclusiveMinimum: 0.0
          title: Size
          type: integer
      required:
      - file_id
      - size
      - sha256_hash
      title: FileInformation
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
<<<<<<< HEAD
=======
    HttpDatasetMissingInformationError:
      additionalProperties: false
      properties:
        data:
          $ref: '#/components/schemas/HttpDatasetMissingInformationErrorData'
        description:
          description: A human readable message to the client explaining the cause
            of the exception.
          title: Description
          type: string
        exception_id:
          const: datasetInformationNotFound
          enum:
          - datasetInformationNotFound
          title: Exception Id
          type: string
      required:
      - data
      - description
      - exception_id
      title: HttpDatasetMissingInformationError
      type: object
    HttpDatasetMissingInformationErrorData:
      properties:
        dataset_id:
          title: Dataset Id
          type: string
        missing_file_ids:
          items:
            type: string
          title: Missing File Ids
          type: array
      required:
      - dataset_id
      - missing_file_ids
      title: HttpDatasetMissingInformationErrorData
      type: object
>>>>>>> ba1695c (WIP batch mode and migration)
    HttpInformationNotFoundError:
      additionalProperties: false
      properties:
        data:
          $ref: '#/components/schemas/HttpInformationNotFoundErrorData'
        description:
          description: A human readable message to the client explaining the cause
            of the exception.
          title: Description
          type: string
        exception_id:
          const: informationNotFound
          enum:
          - informationNotFound
          title: Exception Id
          type: string
      required:
      - data
      - description
      - exception_id
      title: HttpInformationNotFoundError
      type: object
    HttpInformationNotFoundErrorData:
      properties:
        file_id:
          title: File Id
          type: string
      required:
      - file_id
      title: HttpInformationNotFoundErrorData
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.1.0
paths:
<<<<<<< HEAD
=======
  /dataset_information/{dataset_id}:
    get:
      description: Retrieve and serve stored dataset information.
      operationId: getDatasetInformation
      parameters:
      - in: path
        name: dataset_id
        required: true
        schema:
          title: Dataset Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetInformation'
          description:
          - File information consisting of file id, sha256 checksum of the unencrypted
            file content and file size of the unencrypted file in bytes for all files
            in a dataset.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpDatasetMissingInformationError'
          description: 'Exceptions by ID:

            - datasetInformationNotFound: Information for one or more of the dataset
            files is not registered.'
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Return public file information for the given dataset id, i.e. public
        accession.
      tags:
      - FileInformationService
>>>>>>> ba1695c (WIP batch mode and migration)
  /file_information/{file_id}:
    get:
      description: Retrieve and serve stored file information.
      operationId: getFileInformation
      parameters:
      - in: path
        name: file_id
        required: true
        schema:
          title: File Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileInformation'
<<<<<<< HEAD
          description: A configuration or external communication error has occurred
            and details should not be communicated to the client
=======
          description:
          - File information consisting of file id, sha256 checksum of the unencryptedfile
            content and file size of the unencrypted file in bytes.
>>>>>>> ba1695c (WIP batch mode and migration)
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpInformationNotFoundError'
          description: 'Exceptions by ID:

<<<<<<< HEAD
            - informationNotFound: No information registered for the given ID.'
=======
            - informationNotFound: No information registered for the given file ID.'
>>>>>>> ba1695c (WIP batch mode and migration)
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Return public file information for the given file id, i.e. public accession.
      tags:
<<<<<<< HEAD
      - FileIngestService
=======
      - FileInformationService
>>>>>>> ba1695c (WIP batch mode and migration)
  /health:
    get:
      description: Used to test if this service is alive
      operationId: health_health_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: health
      tags:
<<<<<<< HEAD
      - FileIngestService
=======
      - FileInformationService
>>>>>>> ba1695c (WIP batch mode and migration)
