components:
  schemas:
    DatasetFileInformation:
      description: Container bundling public information for a dataset.
      properties:
        accession:
          description: Public accession of a dataset.
          title: Accession
          type: string
        file_information:
          description: Public information on all files belonging to a dataset or only
            the accession,if no detailed information is available.
          items:
            anyOf:
            - $ref: '#/components/schemas/FileAccession'
            - $ref: '#/components/schemas/FileInformation'
          title: File Information
          type: array
      required:
      - accession
      - file_information
      title: DatasetFileInformation
      type: object
    FileAccession:
      description: 'Public identifier for one file information object, representing
        not yet populated

        or already deleted file information objects.'
      properties:
        accession:
          description: Public identifier of the file associated with the given information
          title: Accession
          type: string
      required:
      - accession
      title: FileAccession
      type: object
    FileInformation:
      description: 'Public information container for files registered with the Internal
        File

        Registry service.'
      properties:
        accession:
          description: Public identifier of the file associated with the given information
          title: Accession
          type: string
        sha256_hash:
          description: SHA256 hash of the unencrypted file content encoded as hexadecimal  values
            as produced by hashlib.hexdigest().
          title: Sha256 Hash
          type: string
        size:
          description: Size of the unencrypted file in bytes.
          exclusiveMinimum: 0.0
          title: Size
          type: integer
      required:
      - accession
      - size
      - sha256_hash
      title: FileInformation
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    HttpDatasetNotFoundError:
      additionalProperties: false
      properties:
        data:
          $ref: '#/components/schemas/HttpDatasetNotFoundErrorData'
        description:
          description: A human readable message to the client explaining the cause
            of the exception.
          title: Description
          type: string
        exception_id:
          const: datasetNotFound
          enum:
          - datasetNotFound
          title: Exception Id
          type: string
      required:
      - data
      - description
      - exception_id
      title: HttpDatasetNotFoundError
      type: object
    HttpDatasetNotFoundErrorData:
      properties:
        file_id:
          title: File Id
          type: string
      required:
      - file_id
      title: HttpDatasetNotFoundErrorData
      type: object
    HttpInformationNotFoundError:
      additionalProperties: false
      properties:
        data:
          $ref: '#/components/schemas/HttpInformationNotFoundErrorData'
        description:
          description: A human readable message to the client explaining the cause
            of the exception.
          title: Description
          type: string
        exception_id:
          const: informationNotFound
          enum:
          - informationNotFound
          title: Exception Id
          type: string
      required:
      - data
      - description
      - exception_id
      title: HttpInformationNotFoundError
      type: object
    HttpInformationNotFoundErrorData:
      properties:
        file_id:
          title: File Id
          type: string
      required:
      - file_id
      title: HttpInformationNotFoundErrorData
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.1.0
paths:
  /dataset_information/{dataset_id}:
    get:
      description: Retrieve and serve stored dataset information.
      operationId: getDatasetInformation
      parameters:
      - in: path
        name: dataset_id
        required: true
        schema:
          title: Dataset Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetFileInformation'
          description:
          - File information consisting of file id, sha256 checksum of the unencrypted
            file content and file size of the unencrypted file in bytes for all files
            in a dataset.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpDatasetNotFoundError'
          description: 'Exceptions by ID:

            - datasetNotFound: No information registered for the given dataset ID.'
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Return public file information for the given dataset id, i.e. public
        accession.
      tags:
      - DatsetInformationService
  /file_information/{file_id}:
    get:
      description: Retrieve and serve stored file information.
      operationId: getFileInformation
      parameters:
      - in: path
        name: file_id
        required: true
        schema:
          title: File Id
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileInformation'
          description:
          - File information consisting of file id, sha256 checksum of the unencryptedfile
            content and file size of the unencrypted file in bytes.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpInformationNotFoundError'
          description: 'Exceptions by ID:

            - informationNotFound: No information registered for the given file ID.'
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Return public file information for the given file id, i.e. public accession.
      tags:
      - DatasetInformationService
  /health:
    get:
      description: Used to test if this service is alive
      operationId: health_health_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: health
      tags:
      - DatasetInformationService
